apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    koord-app: koordlet
  name: koordlet
  namespace: koordinator-system
spec:
  minReadySeconds: 10
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      koord-app: koordlet
  template:
    metadata:
      labels:
        koord-app: koordlet
    spec:
      containers:
      - args:
        - -addr=:9316
        - -cgroup-root-dir=/host-cgroup/
        - --logtostderr=true
        - --v=4
        command:
        - /koordlet
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: registry.cn-hangzhou.aliyuncs.com/clay-wangzhi/koordlet:v1.0
        imagePullPolicy: Always
        name: koordlet
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: "0"
            memory: "0"
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
            - SYS_ADMIN
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/localtime
          name: host-time
          readOnly: true
        - mountPath: /host-cgroup/
          name: host-cgroup-root
        - mountPath: /host-sys-fs/
          mountPropagation: Bidirectional
          name: host-sys-fs
        - mountPath: /host-var-run/
          name: host-var-run
          readOnly: true
        - mountPath: /host-run/
          name: host-run
          readOnly: true
        - mountPath: /host-var-run-koordlet/
          mountPropagation: Bidirectional
          name: host-var-run-koordlet
        - mountPath: /prediction-checkpoints
          mountPropagation: Bidirectional
          name: host-koordlet-checkpoint-dir
        - mountPath: /host-sys/
          name: host-sys
          readOnly: true
        - mountPath: /etc/kubernetes/
          name: host-kubernetes
          readOnly: true
        - mountPath: /host-etc-hookserver/
          mountPropagation: Bidirectional
          name: host-etc-hookserver
        - mountPath: /var/lib/kubelet
          name: host-kubelet-rootdir
          readOnly: true
        - mountPath: /dev
          mountPropagation: HostToContainer
          name: host-dev
        - mountPath: /metric-data/
          name: metric-db-path
      dnsPolicy: ClusterFirst
      hostNetwork: true
      hostPID: true
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: koordlet
      serviceAccountName: koordlet
      terminationGracePeriodSeconds: 10
      tolerations:
      - operator: Exists
      volumes:
      - hostPath:
          path: /etc/localtime
          type: ""
        name: host-time
      - hostPath:
          path: /sys/fs/cgroup/
          type: ""
        name: host-cgroup-root
      - hostPath:
          path: /sys/fs/
          type: ""
        name: host-sys-fs
      - hostPath:
          path: /var/run/
          type: ""
        name: host-var-run
      - hostPath:
          path: /run/
          type: ""
        name: host-run
      - hostPath:
          path: /var/run/koordlet
          type: DirectoryOrCreate
        name: host-var-run-koordlet
      - hostPath:
          path: /var/run/koordlet/prediction-checkpoints
          type: DirectoryOrCreate
        name: host-koordlet-checkpoint-dir
      - hostPath:
          path: /sys/
          type: ""
        name: host-sys
      - hostPath:
          path: /etc/kubernetes/
          type: ""
        name: host-kubernetes
      - hostPath:
          path: /etc/runtime/hookserver.d/
          type: ""
        name: host-etc-hookserver
      - hostPath:
          path: /var/lib/kubelet/
          type: ""
        name: host-kubelet-rootdir
      - hostPath:
          path: /dev
          type: ""
        name: host-dev
      - emptyDir:
          medium: Memory
          sizeLimit: 150Mi
        name: metric-db-path
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 20%
    type: RollingUpdate
